services:
  selfbot:
    # Kalau mau rebuild lokal hapus baris image & aktifkan build
    build: .
    image: dachenxi/selfbot-discord:latest
    container_name: selfbot-discord
    env_file: .env
    user: "0:0"  # Run as root untuk mengatasi permission issue di Windows
    volumes:
      - ./data:/app/data:rw
      - ./log:/app/log:rw
    restart: unless-stopped
    # Menggunakan bind mount ke folder lokal dengan permission read-write
    # User diset ke root untuk mengatasi permission error di Windows
    # Folder data dan log akan dapat diakses langsung dari host
    # Tidak expose port karena bot hanya koneksi keluar ke Discord

# Catatan:
# 1. Buat file .env (lihat .env.example) di direktori yang sama untuk inject DISCORD_TOKEN & OWNER_ID.
# 2. User diset ke root (0:0) untuk mengatasi permission error di Windows
# 3. Volume mount menggunakan :rw flag untuk read-write access
# 4. Jalankan: docker compose up -d --build
# 5. Lihat log: docker compose logs -f
# 6. File data dan log dapat diakses langsung dari folder project

# Named volumes dihapus karena sekarang menggunakan bind mount
# volumes:
#   data_store:
#   log_store:
